### ISSUE TITLE
[FIX] 공통 컴포넌트 수정 요청

### ISSUE THREAD

**Issue by dahye1013** [prgrms-fe-devcourse/FEDC2_TimeDivider_Root#11]
# 공통 Component 수정 요청

@ljw0096 

## Navbar

네비게이션 컴포넌트 사용시에 뒤로가기 버튼이 `컨테이너` 해당 영역을 벗어나는 문제가 있어요!

부모 엘리먼트에 `position: relative` 잡고,
뒤로가기 버튼은 `position: absolute`하는 방식으로 수정 요청드려요
<img width="834" alt="Screen Shot 2022-06-08 at 3 21 38 PM" src="https://user-images.githubusercontent.com/64780560/172545893-2c1ee8ff-8bac-4326-9127-61d3eac0203a.png">

## Button 

1. 사이즈 조절하는 옵션
2. display: block, inline 구분 옵션 

하위에서 존재하는 버튼과 추가시 사용되는 버튼 사이즈가 다르게 필요해요.
![Screen Shot 2022-06-08 at 7 35 24 PM](https://user-images.githubusercontent.com/64780560/172596080-c5ebc396-7303-401c-a267-e9048fa86b7c.png)

## Input
onChange 이벤트를 걸수있도록 수정 부탁해요!

## Text
해당 rem이 적용되지 않는데 확인 부탁드려요~ 
font-size={3} prop을 내리는 경우, px로 작동
font-size={'3rem'} 해야만 3rem 으로 반영되네요. 이 부분 확인 부탁할게요~!

#9 
![Screen Shot 2022-06-08 at 7 46 56 PM](https://user-images.githubusercontent.com/64780560/172598169-ef6fed7e-0c67-4741-8934-3f5d34ab690e.png)

## 그 외
구현 된 컴포넌트 prop을 명시적으로 확인 할 수 있도록 
propTypes 지정해주세요 :) 

```js 
Text.propTypes = {
  children: PropTypes.node.isRequired,
  size: PropTypes.oneOfType([PropTypes.number, PropTypes.string]),
  block: PropTypes.bool,
  color: PropTypes.string,
};
```

---

스크럼 하면서 이야기 한 부분들이에요!
수정되면 해당 이슈 어노테이션 달아서 Merge 해주세요 😊

**Comment by ljw0096** [comment]
#12 PR로 요청 반영했습니다.
