### ISSUE TITLE
[FIX] 라우팅 주소 변경 요청

### ISSUE THREAD

**Issue by codeisneverodd** [prgrms-fe-devcourse/FEDC2_TimeDivider_Root#15]
라우터에는 `http://localhost:3000/updateDivider` 로 되어있고

페이지는 `updateTimeDivider`로 되어있어 혼선이 있습니다. 후자로 통일하는 것이 좋아보입니다!

**Comment by dahye1013** [comment]
앗 실수 확인해주셔서 감사해요~ 🙏
현재 라우팅은 페이지 컴포넌트나 path에 대한 구체적으로 논의하지 않은 상황이었어서 임의로 작업되어 있어요!
각자 일정도 있는 상태에서 페이지 작업을 빨리 시작해야해서 작업 분배하려고 ㅎㅎㅎ...!

저는 사실 path와 page 명이 일치할 필요는 없다고 생각해요!
URL에 페이지 컴포넌트 이름을 노출할 필요가 있을까요?
예를 들어 이런식으로도 진행가능하니까요.
- 전체 게시글 
  - path : `post`
  -  page : PostList
  
- 게시글 상세페이지 
  - path : `post/detail/:id`
  -  page : PostDetail

(물론 지금 우선순위로는 혼선을 방지하는게 먼저라 이슈 올리신대로 수정하는게 맞다고 생각해요..!)

이건 한번에 처리할 수 있으니 이후 논의해봐요!
우선은 Issue 올려주신 것 처리하면 Merge해둘게요  ☺️

**Comment by codeisneverodd** [comment]
작업 끝나고 라우팅 네임 한번에 정리하면 좋을 것 같아요. 다혜님이 말씀하신것에 동의합니다!
