### ISSUE TITLE
[FIX] 시간을 분배해요 페이지 수정 요청

### ISSUE THREAD

**Issue by dahye1013** [prgrms-fe-devcourse/FEDC2_TimeDivider_Root#19]
## 선택 된 분배시간 변경 - HOT FIX

특정 분배시간 Select 한 후에 다른 박스를 클릭할때 변경되지 않는 오류가 있어요! 
이건 꼭 고쳐주세요!

https://user-images.githubusercontent.com/64780560/173007362-a853cebe-6a6d-4c76-8ed5-d6aa92fa8ad1.mov

## 시간 미입력시
유저 경험차원에서 두 input 중에 하나만 입력되어도 저장이 되어야한다고 생각해요.
시간 입력은 이건 아예 Select Box로 바꿔서 유저의 인풋을 제어하는게 더 나은 방향인것 같아요.
input=text 오히려 유저 경험이 더 떨어지는 것 같네요.
저랑 같이 논의하고 한번에 바꾸는 방향으로 진행해보죠!

https://user-images.githubusercontent.com/64780560/173007387-75db9b17-66b4-4068-8838-5cd8150d8a18.mov

---

의논이 필요한건 코멘트로 남겨주세요!

**Comment by ljw0096** [comment]
핫픽스 부분은 문제 인지했습니다. 지금 바로 수정 해볼게요.

**Comment by dahye1013** [comment]
셋이서 이슈건 이야기하면서 잘못 올린 수정요청 내용은 수정해두었어요 ㅎㅎ
입력 값은 select box로 수정하기로 이야기 나눴고, 작업중이시니 마저 완료되면 Issue 닫아주세요!

**Comment by dahye1013** [comment]
#25 해당 PR에서 Select Box로 수정된것 확인하여 Issue 닫겠습니다~
