### ISSUE TITLE
[FIX] 시간을 분배해요 페이지 - 유효성 검사 수정 요청

### ISSUE THREAD

**Issue by dahye1013** [prgrms-fe-devcourse/FEDC2_TimeDivider_Root#26]
## 남은 시간 계산 오류
#25 
오류 케이스 
1. 타입스크립트 공부 5시간 할당
2. 남은시간 3시간
3. 타입스크립트 8시간 할당

해당 폼에서 시간을 추가하는 것이 아니고, 업데이트 하는 것이기 때문에 
해당 유효성 검사 로직이 수정되어야 할 것 같아요!

https://user-images.githubusercontent.com/64780560/173195099-eac40b6d-bec2-4e13-b306-abb3469a39bc.mov

기존에 남은 잔여시간에서 selected 된 시간만 빼고 있는 부분인데
```js
		if (totalTime - usedTime < 0) {
			setIsTimeOver(true)
			return
		}
```

selected된 시간과 잔여시간을 더해서 입력 가용시간에 대한 유효성 검증이 필요해보입니다
```js
		const findTask = tasks.find(({ id }) => id === selectedTask.id)
		const availableTime = totalTime + findTask.time
		if (availableTime - usedTime < 0) {
			setIsTimeOver(true)
			return
		}
```

임시로 만든 코드라서 참고만 해주세요!

**Comment by ljw0096** [comment]
다혜님 코드 그대로 적용하니까 바로 수정이 되버렸는데요..?
이렇게 할일 하나를 잃어버렸습니다👍 

제 페이지 리팩토링하면서 올릴때 수정 반영하고 Issue 닫도록 할게요~
