### ISSUE TITLE
[FIX] 불필요한 컴포넌트 존재

### ISSUE THREAD

**Issue by codeisneverodd** [prgrms-fe-devcourse/FEDC2_TimeDivider_Root#40]
첩자를 발견했습니다..
Hello.js는 삭제되어도 되는 컴포넌트 인 것 같은데, 삭제하는 것이 좋아보입니다.
components 폴더가 중복되어 혼선이 생깁니다!
<img width="842" alt="image" src="https://user-images.githubusercontent.com/54318460/173339282-d46b6f45-a5f6-4c12-943f-8fb7b8b7eb48.png">

**Comment by dahye1013** [comment]
헉 저게 뭐죠ㅋㅋㅋㅋ 바로 제거해두겠습니다

**Comment by dahye1013** [comment]
pull 당겨봤는데 없어서 develop 브런치도 확인해봤는데, 존재하지 않는것 같은데요..?
로컬에만 남아있는거 같은데 한번 확인 부탁드려요 ~ !
확인하고 닫도록 하겠습니다 :) 

@codeisneverodd 

![Screen Shot 2022-06-13 at 10 29 54 PM](https://user-images.githubusercontent.com/64780560/173364706-bfd4fa85-d264-41cc-ae15-aba84fb23fb5.png)
