### ISSUE TITLE
[제안] selectBox 클릭 시 나오는 창의 크기와 폰트

### ISSUE THREAD

**Issue by codeisneverodd** [prgrms-fe-devcourse/FEDC2_TimeDivider_Root#47]
select box의 크기가 과도하게 커져서, 선택창이 조금 어색한 것 같은데, selectbox를 클릭했을 때 나오는 창의 크기나 폰트 크기를 작게 조절할 수 있나요? 

<img width="938" alt="image" src="https://user-images.githubusercontent.com/54318460/173406450-1ff3efb7-6241-46d5-8528-5acdfd0cf72e.png">
<img width="603" alt="image" src="https://user-images.githubusercontent.com/54318460/173406787-7c9091ef-74fa-4474-9436-52dbdca09ab6.png">

**Comment by ljw0096** [comment]
박스는 그대로 두고 선택창만 축소시켜야하나요?
