### ISSUE TITLE
[제안] 뒤로가기를 눌렀을 때, 이전 정보가 존재한다면 표시해주기

### ISSUE THREAD

**Issue by codeisneverodd** [prgrms-fe-devcourse/FEDC2_TimeDivider_Root#72]
현재 다음 스텝으로 넘어갔다가, 뒤로 돌아왔을 때 이전에 적었던 정보들이 상태값에는 들어가있지만, 사용자가 보기에는 사라진 것으로 인지됩니다! 뒤로가기를 누르더라도 상태값이 존재한다면 표시를 해주는 것이 좋을 것 같습니다.

<img width="412" alt="image" src="https://user-images.githubusercontent.com/54318460/174301739-15ee36e0-b062-4828-a5b7-e7491c9d25ec.png">
<img width="402" alt="image" src="https://user-images.githubusercontent.com/54318460/174301861-cc8f9177-e70a-4d82-a1f3-eff5d9f1cc7b.png">

**Comment by dahye1013** [comment]
처음에 같이 시안짤때는 단방향 플로우로만 생각해서 일부러 네비게이션바에 뒤로가기를 없앤건데
브라우저 뒤로가기가 지원되니 의미가 없었네요 😅! 

우선 이야기 나눈대로 Recoil 사용해서 전역 상태로 넣어둘게요~
