### ISSUE TITLE
[제안] axios Instance 분리

### ISSUE THREAD

**Issue by ljw0096** [prgrms-fe-devcourse/FEDC2_TimeDivider_Root#81]
![api](https://user-images.githubusercontent.com/81891292/174473912-3d7a1564-635f-449e-85e9-f591a4aaab92.PNG)

기존에 하나의 axiosInstance를 사용하던 형태는

헤더의 Token을 Login 부분에서 주입하는 형태가 어색하다고 생각됩니다.

따라서 2가지 Instance를 각각 token이 필요한 요청, 아닌 요청에 api instance로 사용하는 방법은 어떨까요?

더 좋은 방법이 있다면 댓글 남겨주시기 바랍니다.

우선 Post API 요청작업을 다뤄야 해서 위와 같은 형태로 제 로컬에서 사용은 하고 있겠습니다.

**Comment by dahye1013** [comment]
토큰이 필요한 요청과 토큰이 필요하지 않은 요청은 어떤 기준의 분리이죠?
토큰을 필요하지 않은 요청에 토큰을 왜 보내면 안되는지 잘 모르겠어서 굳이 필요한 작업인가 싶어요.

axios 인스턴스를 싱글톤으로 관리하는게 더 좋다고 생각해요. 어떤 API에는 `A axios 인스턴스`를 사용하고, 어떤 API는 `B axios 인스턴스`를 사용하는 구조는 우선 관리하기 좋지 않을 것 같아요. 두 개의 인스턴스로 나누어지는 순간 관리 대상이 두 개라서 문제가 발생했을 때, 두 번 수정을 거쳐야해서 휴먼 에러가 생길 일이 더 많을 것 같아요.

요청 서버가 두개가 아닌데 이렇게 나눌 필요가 있을까요? 
만약 나눈다면 생성자 함수를 사용해서 똑같은 형태로 `contructor`에 의존성 주입만 다르게 해서 인스턴스를 두개 만들어야 할 것 같긴해요.

차라리 새로 만드신 형태로 통일 시키는게 나을 것 같아요. 
`getToken()`의 역할이 무엇인지는 모르겠지만 (아마 세션 스토리지에서 토큰을 꺼내오는 걸로 추측되는데)
그 형태가 적절하다면 그걸로 기존 코드를 수정하는게 좋을 것 같아요.

`login`에서 주입하는 형태는 저도 좀 어색하게 느껴지긴 해요! 
이건 좀 더 생각해볼게요~

토큰 관련해서 읽어보면 좋은 글을 찾아서 두고 갑니당 총총 

이 Issue와 경현님 PR #88 보면서 Token 관련해서 좀 찾아봤는데 
이후에 해당 작업에 참고하기 좋은 글들이라 여기도 두고 갑니다 ㅎㅎ 
[JWT는 어디에 저장해야할까](https://velog.io/@0307kwon/JWT%EB%8A%94-%EC%96%B4%EB%94%94%EC%97%90-%EC%A0%80%EC%9E%A5%ED%95%B4%EC%95%BC%ED%95%A0%EA%B9%8C-localStorage-vs-cookie) 
[refresh token 도입기](https://tecoble.techcourse.co.kr/post/2021-10-20-refresh-token/)
